[package]
name = "shiber"
version = "0.1.0"
authors = ["LuckShiba <luckshiba@protonmail.com>"]
edition = "2018"

[dependencies]
serenity = "^0.10.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = "^0.11.0"
dotenv = "^0.15.0"
mongodb = "^1.1.1"